export const ADD_TASK = 'ADD_TASK'
export const CLEAR_TASKS = 'CLEAR_TASKS'
export const TOGGLE_MODE = 'TOGGLE_MODE'
export const MOVE_TASK = 'MOVE_TASK'
export const REMOVE_TASK = 'REMOVE_TASK'
export const FINALIZE_TASK = 'FINALIZE_TASK'